# /home/kjm/work/ch11/ex01/github-actions-practice/.github/workflows/main.yml
name: HelloWorld

on: [push]

jobs:
  echo:
    runs-on: ubuntu-latest  
    steps:
    - name: hello
      run: echo "Hello, Github Actions!"
